print ('*'*21)
print ('*   '*5+'*')
print ('*   '*5+'*')
print ('*'*21)
print ('*   '*5+'*')
print ('*   '*5+'*')
print ('*'*21)
print ('*   '*5+'*')
print ('*   '*5+'*')
print ('*'*21)
print ('*   '*5+'*')
print ('*   '*5+'*')
print ('*'*21)
