a = input()
b = float(input())
c = float(input())
d = input()
e = float(input())
f = float(input())
j = ('ИТОГО')
k = format(b,'5.2f')
l = format(c,'5.2f')
m = format(f,'5.2f')
v = format(b*c,"5.2f")
w = format(e*f,"5.2f")
g = float(v) + float(w)
h = round(g, 2)
print('Наименование изделия   Цена  Вес/Кол.   ВСЕГО    ')
print('-------------------- ------- -------- ---------')
print(format(a, "21")  ,format(b,"7.2f") ,format(c,"9.2f"),format(b*c,'10.2f'),sep="")
print(format(d, "21")  ,format(e,"7.2f") ,format(f,"9.2f"),format(e*f,'10.2f'),sep="")
print('-------------------- ------- -------- ---------')
print(format(j, '38'),format(h,"9.2f"),sep="")
